export const FETCH_ALL_NOMINEES_PENDING = "FETCH_ALL_NOMINEES_PENDING";
export const FETCH_ALL_NOMINEES_FULFILLED = "FETCH_ALL_NOMINEES_FULFILLED";
export const FETCH_ALL_NOMINEES_REJECTED = "FETCH_ALL_NOMINEES_REJECTED";

/**
 * Create action types for when the user will vote
 */
